version: '2'

services:
  psql:
    container_name: psql
    image: postgres:alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - otus-spring-hw31-db-local:/var/lib/postgresql/data

volumes:
  otus-spring-hw31-db-local:
    external: true
